#include "se3_fatfs.h"
#include "se3_rand.h"



#pragma pack(push,1) //These are a physical structures, thus we don't want to allow
					// the compiler to insert padding for memory alignment
//Private structures
typedef struct
{
	//Plaintext
	uint8_t nonce_pbkdf2[SEFILE_NONCE_LEN];	/**< 32 random bytes storing the IV for generating a different key*/
	uint32_t key_id;		/**< The ID of the key used to encrypt this file. */
	uint16_t algorithm;		/**< The algorithm used to encrypt this file. */
	uint8_t padding[10];	/**< Padding used to reach a SEkey header size which is a multiple of 16. */

	//Encoded
	uint8_t nonce_ctr[SEFILE_IV_LEN];       /**< 16 random bytes storing the IV for next sectors*/
    int32_t magic;				            /**< 4 bytes used to represent file type (not used yet)*/
    int16_t ver;				            /**< 2 bytes used to represent current filesystem version (not used yet)*/
    int32_t uid;				            /**< 4 bytes not used yet*/
    int32_t uid_cnt;			            /**< 4 bytes not used yet*/
    uint8_t fname_len;			            /**< 1 byte to express how long is the filename.*/
} SEFILE_HEADER;

typedef struct
{
	// notice that the size of the SEFILE_SECTOR does depend on the union. The size of the union is the size of the largest data inside the union (plus memory alignment if any).
	union
	{
        SEFILE_HEADER header;               /**< See \ref SEFILE_HEADER .*/
        uint8_t data[SEFILE_LOGIC_DATA];   /**< In here it will be written the actual data.
											 *   Since it is inside a union data type, the
											 *   filename will be written from 32nd byte.
											 */
    };
    uint16_t len;                      /**< How many bytes are actually stored in this sector.*/
    uint8_t signature[SIGNATURE_LEN];             /**< Authenticated digest generated by the device*/
} SEFILE_SECTOR;

#pragma pack(pop)

//static bool find_and_read_key(uint32_t keyID, se3_fatfs_key* key);
static SE3_FRESULT crypto_filename(char *path, char *enc_name_path, uint16_t *encoded_length);
static SE3_FRESULT crypt_header(uint8_t* input_data, uint8_t* output_data, uint16_t algo, uint32_t keyID, uint16_t direction);
static SE3_FRESULT initialise_crypto_context(uint16_t algo, uint32_t keyID, uint16_t mode, uint32_t* sid);
static SE3_FRESULT set_nonce(uint32_t sid, uint8_t* nonce, uint16_t nonce_len);
static SE3_FRESULT execute_crypto_header(uint32_t sid, uint8_t* input_data, uint8_t* output_data);
static SE3_FRESULT getSHA256string(uint8_t* input, int length, uint8_t* output);
static void get_filename(char *path, char *file_name, int maxLength);
static void get_path(char *full_path, char *path);
static SE3_FRESULT secure_create(SE3_FIL* se_fp, char* path, BYTE mode);
static SE3_FRESULT load_existing_file(SE3_FIL* se_fp, char* path, BYTE mode);

SE3_FRESULT secure_open(SE3_FIL* se_fp, char *path, BYTE mode, uint32_t keyID, uint16_t algo)
{
	SE3_FRESULT res;


	//Create a new file if needed
	if (mode & (FA_CREATE_ALWAYS | FA_CREATE_NEW))
	{
		se_fp->algo = algo;
		se_fp->keyID = keyID;
		return secure_create(se_fp, path, mode);
	}

	//Otherwise open existing
	return load_existing_file(se_fp, path, mode);



	return SE3_FR_OK;
}

static
SE3_FRESULT load_existing_file(SE3_FIL* se_fp, char* path, BYTE mode)
{
	SE3_FRESULT res;
	SEFILE_SECTOR header_sector;
	SEFILE_SECTOR encoded_header_sector;
	UINT br;
	char enc_name_path[MAX_PATHNAME];
	uint16_t encoded_name_length;

	if ((res = crypto_filename(path, enc_name_path, &encoded_name_length)))
		return res;

	//Open the file in read mode in order to read header
	if ((res = f_open(&(se_fp->fp), enc_name_path, FA_READ)))
		return res;

	if((res = f_read(&(se_fp->fp), encoded_header_sector.data, sizeof(SEFILE_SECTOR), &br)))
		return res;

	if (br < sizeof(SEFILE_SECTOR))
		return SE3_FR_HEADER_ENC_ERROR;

	se_fp->algo = encoded_header_sector.header.algorithm;
	se_fp->keyID =  encoded_header_sector.header.key_id;
	if ((res = crypt_header(encoded_header_sector.data, header_sector.data, se_fp->algo, se_fp->keyID, SE3_DIR_DECRYPT)))
		return res;

	memcpy(se_fp->IV, header_sector.header.nonce_ctr, SEFILE_IV_LEN);


	if (mode != FA_READ)
	{
		if ((res = f_close(&(se_fp->fp))))
			return res;

		//reopen file with user selected mode
		if ((res = f_open(&(se_fp->fp), enc_name_path, mode)))
			return res;
	}

	return SE3_FR_OK;
}

static
SE3_FRESULT secure_create(SE3_FIL* se_fp, char* path, BYTE mode)
{
	SE3_FRESULT res;
	char enc_name_path[MAX_PATHNAME];
	uint16_t encoded_name_length;
	char filename[_MAX_LFN];
	uint8_t* padding_start;
	uint8_t* filename_start;
	size_t filename_len;


	//The first sector contains the header only
	SEFILE_SECTOR header_sector;

	uint8_t encoded_header_sector[sizeof(SEFILE_SECTOR)];

	res = crypto_filename(path, enc_name_path, &encoded_name_length);
		if (res != SE3_FR_OK)
			return res;

	res = f_open(&(se_fp->fp), enc_name_path, mode);
	if (res != SE3_FR_OK)
		return res;

	//Prepare header
	se3_rand(SEFILE_NONCE_LEN, (uint8_t*) &(header_sector.header.nonce_pbkdf2));
	header_sector.header.key_id = se_fp->keyID;
	header_sector.header.algorithm = se_fp->algo;
	memset(&(header_sector.header.padding), 0, 10);

	header_sector.header.magic = 0;
	se3_rand(SEFILE_IV_LEN, (uint8_t*) &(header_sector.header.nonce_ctr));
	header_sector.header.uid = 0;
	header_sector.header.uid_cnt = 0;
	header_sector.header.ver = 0;


	get_filename(path, filename, _MAX_LFN);
	filename_len = strnlen(filename, _MAX_LFN);
	header_sector.header.fname_len = filename_len;
	filename_start = header_sector.data + sizeof(SEFILE_HEADER);
	memcpy(filename_start, filename, filename_len);
	padding_start = (uint8_t*) header_sector.data + sizeof(SEFILE_HEADER)+filename_len;
	se3_rand(SEFILE_LOGIC_DATA-sizeof(SEFILE_HEADER)-filename_len, padding_start);
	header_sector.len = sizeof(SEFILE_HEADER) + filename_len;

	if ( (res = crypt_header(header_sector.data, encoded_header_sector, se_fp->algo, se_fp->keyID, SE3_DIR_ENCRYPT) ))
		return res;

	if ((res = f_write(&(se_fp->fp), encoded_header_sector, SE3_FILE_SECTOR_SIZE, NULL)))
		return res;

	return SE3_FR_OK;
}

static
SE3_FRESULT crypt_header(uint8_t* input_data, uint8_t* output_data, uint16_t algo, uint32_t keyID, uint16_t direction)
{
	SE3_FRESULT res;
	uint32_t sid;

	uint8_t *nonce_pbkdf2 = (uint8_t*)input_data;

	if ( (res = initialise_crypto_context(algo, keyID, SE3_FEEDBACK_ECB | direction, &sid)))
		return res;

	if ( (res = set_nonce(sid, nonce_pbkdf2, SEFILE_NONCE_LEN)))
			return res;

	if ( (res = execute_crypto_header(sid, input_data, output_data)))
		return res;

	if (direction == SE3_DIR_DECRYPT)
	{
		if (memcmp(input_data+SE3_SECTOR_ENCRYPTED_DATA_SIZE, output_data+SE3_SECTOR_ENCRYPTED_DATA_SIZE, SIGNATURE_LEN))
			return SE3_FR_INVALID_SIGNATURE;
	}

	return SE3_FR_OK;
}



static
SE3_FRESULT initialise_crypto_context(uint16_t algo, uint32_t keyID, uint16_t mode, uint32_t* sid)
{
	uint8_t request[1024];
	uint8_t response[SE3_CMD1_CRYPTO_INIT_RESP_SIZE];
	uint16_t response_size;

	memcpy(request + SE3_CMD1_CRYPTO_INIT_REQ_OFF_ALGO, &algo, 2);
	memcpy(request + SE3_CMD1_CRYPTO_INIT_REQ_OFF_MODE, &mode, 2);
	memcpy(request + SE3_CMD1_CRYPTO_INIT_REQ_OFF_KEY_ID, &keyID, 4);
	uint16_t rc = crypto_init(SE3_CMD1_CRYPTO_INIT_REQ_SIZE, request, &response_size, response);
	if((rc != SE3_OK) || (response_size != SE3_CMD1_CRYPTO_INIT_RESP_SIZE)){
		return SE3_FR_CYPHER_ERROR;
	}
	memcpy(sid, response+SE3_CMD1_CRYPTO_INIT_RESP_OFF_SID, SE3_CMD1_CRYPTO_INIT_RESP_SIZE); // get session id from crypto_init()
	return SE3_FR_OK;
}

static
SE3_FRESULT set_nonce(uint32_t sid, uint8_t* nonce, uint16_t nonce_len)
{
	uint16_t flags = SE3_CRYPTO_FLAG_SETNONCE;

	uint8_t request[SE3_CRYPTO_MAX_DATAIN];
	uint8_t response[SE3_CRYPTO_MAX_DATAOUT];
	uint16_t response_size = 0;
	uint16_t request_size = 0;

	memcpy(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_SID, &sid, 4);
	memcpy(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_FLAGS, &flags, 2);
	memcpy(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_DATAIN1_LEN, &nonce_len, 2);
	memset(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_DATAIN2_LEN, 0, 2);
	memcpy(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_DATA, nonce, nonce_len);

	request_size = 4 + 2 + 2 + nonce_len;

	if((crypto_update(request_size, request, &response_size, response)) != SE3_OK){
		return SE3_FR_CYPHER_ERROR;
		}

	return SE3_FR_OK;
}

static
SE3_FRESULT execute_crypto_header(uint32_t sid, uint8_t* input_data, uint8_t* output_data)
{
	uint16_t flags = SE3_CRYPTO_FLAG_FINIT | SE3_CRYPTO_FLAG_AUTH;


	size_t datain_len = SE3_SECTOR_ENCRYPTED_DATA_SIZE;
	datain_len -= (SEFILE_NONCE_LEN + SEFILE_HEADER_PLAINTXT_LEN);

	uint8_t request[SE3_CRYPTO_MAX_DATAIN];
	uint8_t response[SE3_CRYPTO_MAX_DATAOUT];
	uint16_t response_size = 0;
	uint16_t request_size = 0;

	memcpy(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_SID, &sid, 4);
	memcpy(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_FLAGS, &flags, 2);
	memset(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_DATAIN1_LEN, 0, 2);
	memcpy(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_DATAIN2_LEN, &datain_len, 2);
	memcpy(request+SE3_CMD1_CRYPTO_UPDATE_REQ_OFF_DATA, input_data + (SEFILE_NONCE_LEN + SEFILE_HEADER_PLAINTXT_LEN), datain_len);

	request_size = 4 + 2 + 2 + datain_len;

	if((crypto_update(request_size, request, &response_size, response)) != SE3_OK){
		return SE3_FR_CYPHER_ERROR;
	}

	memcpy(((uint8_t*)output_data)+SEFILE_NONCE_LEN + SEFILE_HEADER_PLAINTXT_LEN, ((uint8_t*)response) + SE3_CMD1_CRYPTO_UPDATE_RESP_OFF_DATA, response_size-SE3_CMD1_CRYPTO_UPDATE_RESP_OFF_DATA); //copy response data

	memcpy(((uint8_t*)output_data)+SEFILE_NONCE_LEN, ((uint8_t*)input_data)+SEFILE_NONCE_LEN, SEFILE_HEADER_PLAINTXT_LEN); // copy sekey header as plaintext
	memcpy(output_data, input_data, SEFILE_NONCE_LEN); // copy the field named "nonce_pbkdf2" as plaintext into the header

	return SE3_FR_OK;
}

SE3_FRESULT secure_read(SE3_FIL* fp, uint8_t *dataOut, uint32_t dataOut_len, uint32_t *bytesRead)
{
	return f_read(&(fp->fp), dataOut, dataOut_len, (uint*) bytesRead);
}

SE3_FRESULT secure_write(SE3_FIL* fp, uint8_t *dataIn, uint32_t dataIn_len)
{
	UINT bw;
	//f_write(&(fp->fp), fp->keyID, SE3_FATFS_KEY_SIZE, &bw);
	return f_write(&(fp->fp), dataIn, dataIn_len, &bw);
}

SE3_FRESULT secure_close(SE3_FIL* fp)
{
	return f_close(&(fp->fp));
}

/*static
bool find_and_read_key(uint32_t keyID, se3_fatfs_key* key)
{
	se3_flash_it iterator;
	se3_flash_key flashKey;

	flashKey.data = key->data;
	memset(flashKey.data, 0, SE3_FATFS_KEY_SIZE);

	if (!se3_key_find(keyID, &iterator))
		return false;

	se3_key_read(&iterator, &flashKey);

	return true;
}*/

static
SE3_FRESULT crypto_filename(char *path, char *enc_name_path,
		uint16_t *encoded_length)
{
	if ((path == NULL) || (enc_name_path == NULL))
	{
		return SE3_FR_INVALID_NAME;
	}
	uint8_t orig_filename[_MAX_LFN+1];
	uint8_t SHAName[2*B5_SHA256_DIGEST_SIZE+1];
	uint8_t dirPath[MAX_PATHNAME];
	uint16_t lorig;
	int dirPathLen;

	get_filename(path, (char*) orig_filename, _MAX_LFN);
	get_path(path, (char*) dirPath);
	lorig = strnlen((const char*) orig_filename, _MAX_LFN);

	if (strlen((const char*) dirPath) > MAX_PATHNAME - 2 * B5_SHA256_DIGEST_SIZE)
	{
		return SE3_FR_FILENAME_ENC_ERROR;
	}

	getSHA256string(orig_filename, lorig, SHAName);

	dirPathLen = strlen((const char*) dirPath);
	if (encoded_length != NULL)
		*encoded_length = (2*B5_SHA256_DIGEST_SIZE+1) * 2 + dirPathLen;

	if (dirPath[0])
	{
		memcpy(enc_name_path, dirPath, dirPathLen);
	}
	memcpy(enc_name_path + dirPathLen, SHAName, 2*B5_SHA256_DIGEST_SIZE+1);
	return SE3_FR_OK;
}

static
SE3_FRESULT getSHA256string(uint8_t* input, int length, uint8_t* output)
{
	B5_tSha256Ctx ctx;
	uint8_t bufferName[B5_SHA256_DIGEST_SIZE];
	uint16_t i;

	if ((B5_SHA256_RES_OK != B5_Sha256_Init(&ctx)))
	{
		return SE3_FR_FILENAME_ENC_ERROR;
	}
	if ((B5_SHA256_RES_OK != B5_Sha256_Update(&ctx, (uint8_t*) input, length)))
	{
		return SE3_FR_FILENAME_ENC_ERROR;
	}
	if ((B5_SHA256_RES_OK != B5_Sha256_Finit(&ctx, (uint8_t*) bufferName)))
	{
		return SE3_FR_FILENAME_ENC_ERROR;
	}

	for (i = 0; i < B5_SHA256_DIGEST_SIZE; i++)
	{
		sprintf((char*) &(output[i * 2]), "%02x", (uint8_t) bufferName[i]);
	}

	return SE3_FR_OK;
}

static
void get_path(char *full_path, char *path)
{
	if ((full_path == NULL) || (path == NULL))
	{
		return;
	}
	char *p_name;
	p_name = strrchr(full_path, '/');
	if (p_name == NULL)
	{
		p_name = strrchr(full_path, '\\');
		if (p_name == NULL)
		{
			path[0] = '\0';
		}
		else
		{
			memcpy(path, full_path, p_name - full_path + 1);
			path[p_name - full_path + 1] = '\0';
		}
	}
	else
	{
		memcpy(path, full_path, p_name - full_path + 1);
		path[p_name - full_path + 1] = '\0';
	}
}

static
void get_filename(char *path, char *file_name, int maxLength)
{
	if ((file_name == NULL) || (path == NULL))
	{
		return;
	}
	char *f_name;
	f_name = strrchr(path, '/');
	if (f_name == NULL)
	{
		f_name = strrchr(path, '\\');
		if (f_name == NULL)
		{
			strncpy(file_name, path, maxLength);
		}
		else
		{
			strncpy(file_name, f_name + 1, maxLength);
		}
	}
	else
	{
		strncpy(file_name, f_name + 1, maxLength);
	}
}
