#include "se3_fatfs.h"

#define SEFILE_NONCE_LEN 32
#define SIGNATURE_LEN 32
#define SEFILE_LOGIC_DATA _MAX_SS - sizeof(uint16_t) - SIGNATURE_LEN

#pragma pack(push,1) //These are a physical structures, thus we don't want to allow
					// the compiler to insert padding for memory alignment
//Private structures
typedef struct
{
	uint8_t nonce_pbkdf2[SEFILE_NONCE_LEN];	/**< 32 random bytes storing the IV for generating a different key*/
	uint32_t key_id;		/**< The ID of the key used to encrypt this file. */
	uint16_t algorithm;		/**< The algorithm used to encrypt this file. */
	uint8_t padding[10];	/**< Padding used to reach a SEkey header size which is a multiple of 16. */
	uint8_t nonce_ctr[16];		            /**< 16 random bytes storing the IV for next sectors*/
    int32_t magic;				            /**< 4 bytes used to represent file type (not used yet)*/
    int16_t ver;				            /**< 2 bytes used to represent current filesystem version (not used yet)*/
    int32_t uid;				            /**< 4 bytes not used yet*/
    int32_t uid_cnt;			            /**< 4 bytes not used yet*/
    uint8_t fname_len;			            /**< 1 byte to express how long is the filename.*/
} SEFILE_HEADER;

typedef struct
{
	// notice that the size of the SEFILE_SECTOR does depend on the union. The size of the union is the size of the largest data inside the union (plus memory alignment if any).
	union
	{
        SEFILE_HEADER header;               /**< See \ref SEFILE_HEADER .*/
        uint8_t data[SEFILE_LOGIC_DATA];   /**< In here it will be written the actual data.
											 *   Since it is inside a union data type, the
											 *   filename will be written from 32nd byte.
											 */
    };
    uint16_t len;                      /**< How many bytes are actually stored in this sector.*/
    uint8_t signature[SIGNATURE_LEN];             /**< Authenticated digest generated by the device*/
} SEFILE_SECTOR;

#pragma pack(pop)

static bool find_and_read_key(uint32_t keyID, se3_fatfs_key* key);
static SE3_FRESULT crypto_filename(char *path, char *enc_name_path, uint16_t *encoded_length);
static SE3_FRESULT getSHA256string(uint8_t* input, int length, uint8_t* output);
static void get_filename(char *path, char *file_name, int maxLength);
static void get_path(char *full_path, char *path);
static SE3_FRESULT secure_create(SE3_FIL* se_fp, char* path, BYTE mode);

SE3_FRESULT secure_open(SE3_FIL* se_fp, char *path, BYTE mode, uint32_t keyID, uint16_t algo)
{
	SE3_FRESULT res;
	char enc_name_path[MAX_PATHNAME];
	uint16_t encoded_name_length;

	if(! find_and_read_key(keyID, &(se_fp->key)))
		return SE3_FR_NO_KEY;

	res = crypto_filename(path, enc_name_path, &encoded_name_length);
	if (res != SE3_FR_OK)
		return res;


	//Create a new file if needed
/*	if (mode & (FA_CREATE_ALWAYS | FA_CREATE_NEW))
	{
		return secure_create(se_fp, enc_name_path, mode);
	}
*/
	//Otherwise open existing
	res = f_open(&(se_fp->fp), enc_name_path, mode);
	if (res != SE3_FR_OK)
		return res;

	return SE3_FR_OK;
}

static
SE3_FRESULT secure_create(SE3_FIL* se_fp, char* enc_name_path, BYTE mode)
{
	SE3_FRESULT res;

	//The first sector contains the header only
	SEFILE_SECTOR header_sector;

	res = f_open(&(se_fp->fp), enc_name_path, mode);
	if (res != SE3_FR_OK)
		return res;

	header_sector.header.key_id = se_fp->key.id;
	header_sector.header.algorithm = se_fp->algo;



	return SE3_FR_OK;
}

SE3_FRESULT secure_read(SE3_FIL* fp, uint8_t *dataOut, uint32_t dataOut_len, uint32_t *bytesRead)
{
	return f_read(&(fp->fp), dataOut, dataOut_len, (uint*) bytesRead);
}

SE3_FRESULT secure_write(SE3_FIL* fp, uint8_t *dataIn, uint32_t dataIn_len)
{
	UINT bw;
	f_write(&(fp->fp), fp->key.data, SE3_FATFS_KEY_SIZE, &bw);
	return f_write(&(fp->fp), dataIn, dataIn_len, &bw);
}

SE3_FRESULT secure_close(SE3_FIL* fp)
{
	return f_close(&(fp->fp));
}

static
bool find_and_read_key(uint32_t keyID, se3_fatfs_key* key)
{
	se3_flash_it iterator;
	se3_flash_key flashKey;

	flashKey.data = key->data;
	memset(flashKey.data, 0, SE3_FATFS_KEY_SIZE);

	if (!se3_key_find(keyID, &iterator))
		return false;

	se3_key_read(&iterator, &flashKey);

	return true;
}

static
SE3_FRESULT crypto_filename(char *path, char *enc_name_path,
		uint16_t *encoded_length)
{
	if ((path == NULL) || (enc_name_path == NULL))
	{
		return SE3_FR_INVALID_NAME;
	}
	uint8_t orig_filename[_MAX_LFN+1];
	uint8_t SHAName[2*B5_SHA256_DIGEST_SIZE+1];
	uint8_t dirPath[MAX_PATHNAME];
	uint16_t lorig;
	int dirPathLen;

	get_filename(path, (char*) orig_filename, _MAX_LFN);
	get_path(path, (char*) dirPath);
	lorig = strnlen((const char*) orig_filename, _MAX_LFN);

	if (strlen((const char*) dirPath) > MAX_PATHNAME - 2 * B5_SHA256_DIGEST_SIZE)
	{
		return SE3_FR_FILENAME_ENC_ERROR;
	}

	getSHA256string(orig_filename, lorig, SHAName);

	dirPathLen = strlen((const char*) dirPath);
	if (encoded_length != NULL)
		*encoded_length = (2*B5_SHA256_DIGEST_SIZE+1) * 2 + dirPathLen;

	if (dirPath[0])
	{
		memcpy(enc_name_path, dirPath, dirPathLen);
	}
	memcpy(enc_name_path + dirPathLen, SHAName, 2*B5_SHA256_DIGEST_SIZE+1);
	return SE3_FR_OK;
}

static
SE3_FRESULT getSHA256string(uint8_t* input, int length, uint8_t* output)
{
	B5_tSha256Ctx ctx;
	uint8_t bufferName[B5_SHA256_DIGEST_SIZE];
	uint16_t i;

	if ((B5_SHA256_RES_OK != B5_Sha256_Init(&ctx)))
	{
		return SE3_FR_FILENAME_ENC_ERROR;
	}
	if ((B5_SHA256_RES_OK != B5_Sha256_Update(&ctx, (uint8_t*) input, length)))
	{
		return SE3_FR_FILENAME_ENC_ERROR;
	}
	if ((B5_SHA256_RES_OK != B5_Sha256_Finit(&ctx, (uint8_t*) bufferName)))
	{
		return SE3_FR_FILENAME_ENC_ERROR;
	}

	for (i = 0; i < B5_SHA256_DIGEST_SIZE; i++)
	{
		sprintf((char*) &(output[i * 2]), "%02x", (uint8_t) bufferName[i]);
	}

	return SE3_FR_OK;
}

static
void get_path(char *full_path, char *path)
{
	if ((full_path == NULL) || (path == NULL))
	{
		return;
	}
	char *p_name;
	p_name = strrchr(full_path, '/');
	if (p_name == NULL)
	{
		p_name = strrchr(full_path, '\\');
		if (p_name == NULL)
		{
			path[0] = '\0';
		}
		else
		{
			memcpy(path, full_path, p_name - full_path + 1);
			path[p_name - full_path + 1] = '\0';
		}
	}
	else
	{
		memcpy(path, full_path, p_name - full_path + 1);
		path[p_name - full_path + 1] = '\0';
	}
}

static
void get_filename(char *path, char *file_name, int maxLength)
{
	if ((file_name == NULL) || (path == NULL))
	{
		return;
	}
	char *f_name;
	f_name = strrchr(path, '/');
	if (f_name == NULL)
	{
		f_name = strrchr(path, '\\');
		if (f_name == NULL)
		{
			strncpy(file_name, path, maxLength);
		}
		else
		{
			strncpy(file_name, f_name + 1, maxLength);
		}
	}
	else
	{
		strncpy(file_name, f_name + 1, maxLength);
	}
}
